In [5]:
import pandas as pd

# Step 1: Read the data from the confirmed CSV file
confirmed_file = 'rawData/monthly_confirmed.csv'
df_confirmed = pd.read_csv(confirmed_file)

# Step 2: Fill missing values in "Province/State" column with null
df_confirmed["Province/State"].fillna(value='unknown', inplace=True)

# Step 3: Melt the data to unpivot the date columns
id_vars =  ["Province/State","Country/Region","Lat","Long"]
df_confirmed_melted = df_confirmed.melt(id_vars=id_vars, var_name="date", value_name="confirmed")

# Step 4: Rename the "Country/Region" column to "Country_Region"
df_confirmed_melted.rename(columns={'Country/Region': 'Country_Region'}, inplace=True)

# Step 5: Rename the "Province/State" column to "Province_State"
df_confirmed_melted.rename(columns={'Province/State': 'Province_State'}, inplace=True)

# Step 5 (Continued): Drop rows with missing or invalid latitude and longitude
df_confirmed_melted = df_confirmed_melted.dropna(subset=['Lat', 'Long'], how='any')
df_confirmed_melted = df_confirmed_melted[(df_confirmed_melted['Lat'] != 0) | (df_confirmed_melted['Long'] != 0)]


# Step 6: Convert the "date" column to a consistent date format (e.g., 'YYYY-MM')
df_confirmed_melted['date'] = pd.to_datetime(df_confirmed_melted['date'], format='%B/%y').dt.strftime('%Y-%m')

# Step 6 (Continued): Convert latitude and longitude values to appropriate format
df_confirmed_melted['Lat'] = df_confirmed_melted['Lat'].astype(float)
df_confirmed_melted['Long'] = df_confirmed_melted['Long'].astype(float)

# Step 7: Optionally, sort the data frame by country and date
df_confirmed_final = df_confirmed_melted.sort_values(by=["date"]).reset_index(drop=True)

# Display the final data frame
df_confirmed_final.head(100)

   Province_State  Country_Region        Lat        Long     date  confirmed
0         unknown     Afghanistan  33.939110   67.709953  2020-01        0.0
1         unknown      Micronesia   7.425600  150.550800  2020-01        0.0
2         unknown         Moldova  47.411600   28.369900  2020-01        0.0
3         unknown          Monaco  43.733300    7.416700  2020-01        0.0
4         unknown        Mongolia  46.862500  103.846700  2020-01        0.0
..            ...             ...        ...         ...      ...        ...
95        unknown         Tunisia  33.886917    9.537499  2020-01        0.0
96        unknown       Venezuela   6.423800  -66.589700  2020-01        0.0
97        unknown      Uzbekistan  41.377491   64.585262  2020-01        0.0
98        unknown         Uruguay -32.522800  -55.765800  2020-01        0.0
99        unknown  United Kingdom  55.378100   -3.436000  2020-01        2.0

[100 rows x 6 columns]

In [6]:
import pandas as pd

# Step 1: Read the data from the deaths CSV file
deaths_file = 'rawData/monthly_deaths.csv'
df_deaths = pd.read_csv(deaths_file)

# Step 2: Fill missing values in "Province/State" column with null
df_deaths["Province/State"].fillna(value='unknown', inplace=True)

# Step 3: Melt the data to unpivot the date columns
id_vars =  ["Province/State","Country/Region","Lat","Long"]
df_deaths_melted = df_deaths.melt(id_vars=id_vars, var_name="date", value_name="deaths")

# Step 4: Rename the "Country/Region" column to "Country_Region"
df_deaths_melted.rename(columns={'Country/Region': 'Country_Region'}, inplace=True)

# Step 5: Rename the "Province/State" column to "Province_State"
df_deaths_melted.rename(columns={'Province/State': 'Province_State'}, inplace=True)

# Step 6: Convert the "date" column to a consistent date format (e.g., 'YYYY-MM')
df_deaths_melted['date'] = pd.to_datetime(df_deaths_melted['date'], format='%B/%y').dt.strftime('%Y-%m')

# Step 7: Drop rows with missing or invalid latitude and longitude
df_deaths_melted = df_deaths_melted.dropna(subset=['Lat', 'Long'], how='any')
df_deaths_melted = df_deaths_melted[(df_deaths_melted['Lat'] != 0) | (df_deaths_melted['Long'] != 0)]


# Step 8: Convert latitude and longitude values to appropriate format
df_deaths_melted['Lat'] = df_deaths_melted['Lat'].astype(float)
df_deaths_melted['Long'] = df_deaths_melted['Long'].astype(float)

# Step 9: Optionally, sort the data frame by country and date
df_deaths_final = df_deaths_melted.sort_values(by=["date"]).reset_index(drop=True)

# Display the final data frame
df_deaths_final.head(100)

   Province_State  Country_Region        Lat        Long     date  deaths
0         unknown     Afghanistan  33.939110   67.709953  2020-01       0
1         unknown      Micronesia   7.425600  150.550800  2020-01       0
2         unknown         Moldova  47.411600   28.369900  2020-01       0
3         unknown          Monaco  43.733300    7.416700  2020-01       0
4         unknown        Mongolia  46.862500  103.846700  2020-01       0
..            ...             ...        ...         ...      ...     ...
95        unknown         Tunisia  33.886917    9.537499  2020-01       0
96        unknown       Venezuela   6.423800  -66.589700  2020-01       0
97        unknown      Uzbekistan  41.377491   64.585262  2020-01       0
98        unknown         Uruguay -32.522800  -55.765800  2020-01       0
99        unknown  United Kingdom  55.378100   -3.436000  2020-01       2

[100 rows x 6 columns]

In [7]:
import pandas as pd

# Step 1: Read the data from the recovery CSV file
recovery_file = 'rawData/monthly_recovery.csv'
df_recovery = pd.read_csv(recovery_file)

# Step 2: Fill missing values in "Province/State" column with null
df_recovery["Province/State"].fillna(value='unknown', inplace=True)

# Step 3: Melt the data to unpivot the date columns
id_vars =  ["Province/State","Country/Region","Lat","Long"]
df_recovery_melted = df_recovery.melt(id_vars=id_vars, var_name="date", value_name="recovery")

# Step 4: Rename the "Country/Region" column to "Country_Region"
df_recovery_melted.rename(columns={'Country/Region': 'Country_Region'}, inplace=True)

# Step 5: Rename the "Province/State" column to "Province_State"
df_recovery_melted.rename(columns={'Province/State': 'Province_State'}, inplace=True)

# Step 6: Convert the "date" column to a consistent date format (e.g., 'YYYY-MM')
df_recovery_melted['date'] = pd.to_datetime(df_recovery_melted['date'], format='%B/%y').dt.strftime('%Y-%m')

# Step 7: Drop rows with missing or invalid latitude and longitude
df_recovery_melted = df_recovery_melted.dropna(subset=['Lat', 'Long'], how='any')
df_recovery_melted = df_recovery_melted[(df_recovery_melted['Lat'] != 0) | (df_recovery_melted['Long'] != 0)]


# Step 8: Convert latitude and longitude values to appropriate format
df_recovery_melted['Lat'] = df_recovery_melted['Lat'].astype(float)
df_recovery_melted['Long'] = df_recovery_melted['Long'].astype(float)

# Step 9: Optionally, sort the data frame by country and date
df_recovery_final = df_recovery_melted.sort_values(by=["date"]).reset_index(drop=True)

# Display the final data frame
df_recovery_final.head(100)

,Province_State,Country_Region,Lat,Long,date,recovery
0,unknown,Afghanistan,33.939110,67.709953,2020-01,0
1,unknown,Montenegro,42.708678,19.374390,2020-01,0
2,unknown,Morocco,31.791700,-7.092600,2020-01,0
3,unknown,Mozambique,-18.665700,35.529600,2020-01,0
4,unknown,Namibia,-22.957600,18.490400,2020-01,0
...,...,...,...,...,...,...
95,unknown,Winter Olympics 2022,39.904200,116.407400,2020-01,0
96,unknown,Yemen,15.552727,48.516388,2020-01,0
97,unknown,Zambia,-13.133897,27.849332,2020-01,0
98,unknown,Zimbabwe,-19.015438,29.154857,2020-01,0
99,Montserrat,United Kingdom,16.742498,-62.187366,2020-01,0

In [10]:
import sqlite3
import pandas as pd

# Create SQLite database and tables
conn = sqlite3.connect('../database/dashboard_data.db')
df_confirmed_final.to_sql('confirmed', conn, if_exists='replace', index=False)
df_deaths_final.to_sql('deaths', conn, if_exists='replace', index=False)
df_recovery_final.to_sql('recovery', conn, if_exists='replace', index=False)

# Verify the database
query = "SELECT * FROM confirmed LIMIT 5;"
result = conn.execute(query).fetchall()
print(result)

[('unknown', 'Afghanistan', 33.93911, 67.709953, '2020-01', 0.0), ('unknown', 'Micronesia', 7.4256, 150.5508, '2020-01', 0.0), ('unknown', 'Moldova', 47.4116, 28.3699, '2020-01', 0.0), ('unknown', 'Monaco', 43.7333, 7.4167, '2020-01', 0.0), ('unknown', 'Mongolia', 46.8625, 103.8467, '2020-01', 0.0)]

In [12]:
# Connect to the SQLite database
conn = sqlite3.connect('../database/dashboard_data.db')
cursor = conn.cursor()

# Get the list of tables in the database
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()

# Print the table names
print("Tables in dashboard_data.db:")
for table in tables:
    print(table[0])

# Close the database connection
conn.close()

Tables in dashboard_data.db:
confirmed
deaths
recovery

In [13]:
import sqlite3

# Connect to the SQLite database
conn = sqlite3.connect('../database/dashboard_data.db')
cursor = conn.cursor()

# Function to get column names of a table
def get_column_names(table_name):
    cursor.execute(f"PRAGMA table_info({table_name});")
    columns = cursor.fetchall()
    return [column[1] for column in columns]

# Get the list of tables in the database
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()

# Print column names for each table
for table in tables:
    table_name = table[0]
    print(f"Columns in {table_name}:")
    columns = get_column_names(table_name)
    print(columns)

# Close the database connection
conn.close()

Columns in confirmed:
['Province_State', 'Country_Region', 'Lat', 'Long', 'date', 'confirmed']
Columns in deaths:
['Province_State', 'Country_Region', 'Lat', 'Long', 'date', 'deaths']
Columns in recovery:
['Province_State', 'Country_Region', 'Lat', 'Long', 'date', 'recovery']